### ISSUE TITLE
Error: Call to undefined function create_function() on Igor with PHP 8.0

### ISSUE THREAD

**Issue by myfirstnameispaul** [turnermm/codedoc#8]
Pages using codedoc fail to load and an error is generated in the logs:

```text
2022-08-09 17:15:34Error: Call to undefined function create_function() /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/lib/plugins/codedoc/syntax/specials.php(67)
    #0 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/parser/renderer.php(117): syntax_plugin_codedoc_specials->render()
    #1 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/parserutils.php(682): Doku_Renderer->plugin()
    #2 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/parserutils.php(149): p_render()
    #3 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/parserutils.php(89): p_cached_output()
    #4 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/Ui/PageView.php(68): p_wiki_xhtml()
    #5 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #6 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #7 [internal function]: tpl_content_core()
    #8 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/Extension/Event.php(133): call_user_func_array()
    #9 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger()
    #10 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger()
    #11 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/lib/tpl/dokuwiki/main.php(59): tpl_content()
    #12 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/inc/actions.php(27): include('...')
    #13 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/doku.php(126): act_dispatch()
    #14 /home/username/local_html/dokuwiki-2022-7-31/dokuwiki/index.php(76): require('...')
    #15 {main}
```

This is being run locally in Linux Mint using `php8.0 -S localhost:8008 index.php`.

When I run `php7.4 -S localhost:8008 index.php` there are no problems, so it seems maybe an issue related to PHP8.0?

**Comment by turnermm** [comment]
Should be fixed
