### ISSUE TITLE
PHP 8 Compatibility

### ISSUE THREAD

**Issue by punk-t** [turnermm/codedoc#9]
As of EOL of PHP 7.4 many hosters disable these older versions of PHP.

This plugin seems still not to be compatible to higher versions.

```
Error: Call to undefined function create_function()
/var/www/virtual/punk1t/punk-t.de/wiki/lib/plugins/codedoc/syntax/specials.php(67)
#0 /var/www/virtual/punk1t/punk-t.de/wiki/inc/parser/renderer.php(117): syntax_plugin_codedoc_specials->render('xhtml', Object(renderer_plugin_xbr), Array)
#1 /var/www/virtual/punk1t/punk-t.de/wiki/inc/parserutils.php(682): Doku_Renderer->plugin('codedoc_special...', Array, 5, '~~codedoc:Ein K...')
#2 /var/www/virtual/punk1t/punk-t.de/wiki/inc/parserutils.php(149): p_render('xhtml', Array, NULL)
#3 /var/www/virtual/punk1t/punk-t.de/wiki/inc/parserutils.php(89): p_cached_output('/var/www/virtua...', 'xhtml', 'playground:star...')
#4 /var/www/virtual/punk1t/punk-t.de/wiki/inc/Ui/PageView.php(68): p_wiki_xhtml('playground:star...', 0, true, '')
#5 /var/www/virtual/punk1t/punk-t.de/wiki/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
#6 /var/www/virtual/punk1t/punk-t.de/wiki/inc/template.php(100): dokuwiki\Action\Show->tplContent()
#7 [internal function]: tpl_content_core('show')
#8 /var/www/virtual/punk1t/punk-t.de/wiki/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
#9 /var/www/virtual/punk1t/punk-t.de/wiki/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
#10 /var/www/virtual/punk1t/punk-t.de/wiki/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
#11 /var/www/virtual/punk1t/punk-t.de/wiki/lib/tpl/dokuwiki/main.php(59): tpl_content()
#12 /var/www/virtual/punk1t/punk-t.de/wiki/inc/actions.php(27): include('/var/www/virtua...')
#13 /var/www/virtual/punk1t/punk-t.de/wiki/doku.php(126): act_dispatch()
```

**Comment by punk-t** [comment]
Sorry, it was already fixed. Lokkes like I used an older version.
